FROM golang:1.16-alpine

# Download packages

RUN apk add --no-cache git

# Set the Current Working Directory inside the container

WORKDIR /app

# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /docker-gs-ping

# Create non root user
RUN addgroup -g 1050 -S limitedaccessaccount && \
    adduser -u 1050 -S limitedaccessaccount -G limitedaccessaccount

# Set non root user
USER 1050

EXPOSE 8080

CMD [ "/docker-gs-ping" ]

