{{ range .Values.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required "Each entry in configFiles needs a configMapName" .configMapName }}
  labels:
    {{- include "chart.basicLabels" $ | nindent 4 }}
data: 
{{- range $path, $_ := $.Files.Glob .fileGlob }}
{{- $path | base | nindent 2 }}: |-
{{- $.Files.Get $path | nindent 4 }}
{{- end }}
{{- end }}

