{{ if .Values.configData }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.basicLabels" . | nindent 4 }}
data:
{{ toYaml .Values.configData | indent 2 }}
{{ end }}