{{- if .Values.extraDeployment.enabled -}}
{{- range .Values.extraDeployment.deployments }}
{{- $deploymentName := (required "Each entry in extraDeployment.deployments needs a name" .name) }}
{{- $dictOfBasicLabels := include "chart.basicLabels" $ | fromYaml }}
{{- $dictOfBasicSelectorLabels := include "chart.basicSelectorLabels" $ | fromYaml }}
{{- $deploymentFullName := printf "%s-%s" (include "chart.fullname" $ | trunc 40) .name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentFullName }}
  labels:
    {{- range $k, $v := $dictOfBasicLabels }}
    {{- if eq $k "app" }}
    {{ $k }}: {{ $deploymentFullName }}
    {{- else}}
    {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
spec:
  replicas: {{ required "Each entry in extraDeployment.deployments needs a replicaCount" .replicaCount }}
  selector:
    matchLabels:
      {{- range $k, $v := $dictOfBasicSelectorLabels }}
      {{- if eq $k "app" }}
      {{ $k }}: {{ $deploymentFullName }}
      {{- else}}
      {{ $k }}: {{ $v }}
      {{- end }}
      {{- end }}
  template:
    metadata:
      annotations:
        checksum/{{ include "chart.fullname" $ }}-configmap: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
        checksum/{{ include "chart.fullname" $ }}-secret: {{ include (print $.Template.BasePath "/secret.yaml") $ | sha256sum }}
        {{- if not $.Values.istio.enabled }}
        sidecar.istio.io/inject: "false"
        {{- end }}
        {{- include "chart.buildExtraAnnotations" (dict "excludeGlobalExtraAnnotations" .excludeGlobalExtraAnnotations "extraAnnotations" .extraAnnotations "values" $.Values) | indent 8 }}
      labels:
        {{- range $k, $v := $dictOfBasicLabels }}
        {{- if eq $k "app" }}
        {{ $k }}: {{ $deploymentFullName }}
        {{- else}}
        {{ $k }}: {{ $v }}
        {{- end }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: {{ include "chart.fullname" $ }}
      enableServiceLinks: {{ $.Values.enableServiceLinks }}
      securityContext:
        fsGroup: {{ $.Values.podSecurityContext.fsGroup }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  {{- range $k, $v := $dictOfBasicSelectorLabels }}
                  - key: {{ $k | quote }}
                    operator: In
                    values:
                      {{- if eq $k "app" }}
                      - {{ $deploymentFullName | quote }}
                      {{- else }}
                      - {{ $v | quote }}
                  {{- end }}
                  {{- end }}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ $deploymentFullName | quote }}
          image: {{ include "chart.buildImagePath" (dict "image" .image "values" $.Values ) | quote }}
{{/*          {{- if (dig "image" "pullPolicy" "" (default dict .image)) }}*/}}
          {{- if (and .image (default dict .image).pullPolicy) }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- else }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- end }}
          securityContext:
            {{- toYaml (merge dict $.Values.securityContext (or .securityContext dict)) | nindent 12}}
          ports:
            - containerPort: {{ required "Each entry in extraDeployment.deployments needs a port" .port }}

          {{- if .command }}
          command: [{{ .command | quote }}]
          {{- end }}

          {{- if .args }}
          args:
            {{- toYaml .args | nindent 10 }}
          {{- end }}

          {{- if .env }}
          env:
          {{- range $k, $v := .env }}
          - name: {{ $k | quote}}
            value: {{ $v | quote }}
          {{- end }}
          {{- end }}

          {{- if or $.Values.configData $.Values.secretData}}
          envFrom:
          {{- if $.Values.configData }}
          - configMapRef:
              name: {{ include "chart.fullname" $ }}
          {{- end }}
          {{- if $.Values.secretData }}
          - secretRef:
              name: {{ include "chart.fullname" $ }}
          {{- end }}
          {{- end }}

          {{- with $.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with $.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- if .resources}}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- else }}
          {{- with $.Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}

      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if or .volumes (and $.Values.volumes (ne .excludeGlobalVolumes true)) }}
      volumes:
      {{- if and $.Values.volumes (ne .excludeGlobalVolumes true) }}
      {{- toYaml $.Values.volumes | nindent 6 }}
      {{- end }}
      {{- if .volumes }}
      {{- toYaml .volumes | nindent 6 }}
      {{- end }}
      {{- end }}

{{- end }}
{{- end }}


{{- if .Values.extraDeployment.hpaExtra.enabled -}}
{{- range .Values.extraDeployment.deployments }}
{{- $deploymentName := (required "Each entry in extraDeployment.deployments needs a name" .name) }}
{{- $deploymentFullName := printf "%s-%s" (include "chart.fullname" $ | trunc 40) $deploymentName }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $deploymentFullName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $deploymentFullName }}
  minReplicas: {{ required "if extraDeployment has hpaExtra enabled, each deployment must have minPods and maxPods set" .minPods }}
  maxReplicas: {{ required "if extraDeployment has hpaExtra enabled, each deployment must have minPods and maxPods set" .maxPods }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ required "if extraDeployment has hpaExtra enabled, each deployment must have cpuAverageUtilizationThreshold set" .cpuAverageUtilizationThreshold }}
{{- end }}
{{- end }}


{{- if .Values.extraDeployment.enabled -}}
{{- range .Values.extraDeployment.deployments }}
{{- $deploymentName := (required "Each entry in extraDeployment.deployments needs a name" .name) }}
{{- $dictOfBasicLabels := include "chart.basicLabels" $ | fromYaml }}
{{- $dictOfBasicSelectorLabels := include "chart.basicSelectorLabels" $ | fromYaml }}
{{- $deploymentFullName := printf "%s-%s" (include "chart.fullname" $ | trunc 40) $deploymentName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $deploymentFullName }}
  labels:
    {{- range $k, $v := $dictOfBasicLabels }}
    {{- if eq $k "app" }}
    {{ $k }}: {{ $deploymentFullName }}
    {{- else}}
    {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
spec:
  type: {{ default "ClusterIP" .serviceType }}
  ports:
    - port: {{ .port }}
      targetPort: {{ or .targetPort .port }}
      name: http
  selector:
      {{- range $k, $v := $dictOfBasicSelectorLabels }}
      {{- if eq $k "app" }}
      {{ $k }}: {{ $deploymentFullName }}
      {{- else}}
      {{ $k }}: {{ $v }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
