{{- if .Values.image.credentials.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
  labels:
    {{- include "chart.basicLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
{{/*  TODO: does this template need to be created?  */}}
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
