{{- if .Values.istio.enabled -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.basicLabels" . | nindent 4 }}
spec:
  {{- with .Values.istio.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.istio.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  http:
  - match:
    - headers:
        'X-Forwarded-Proto':
          exact: http
    redirect:
      scheme: https
      redirectCode: 301
  - match:
    {{- range .Values.istio.paths }}
    - uri:
        prefix: {{ . }}
      headers:
        'X-Forwarded-Proto':
          exact: https
    {{- end }}
    route:
    - destination:
        host: {{ include "chart.fullname" . }}
        port:
          number: {{ .Values.service.port }}


---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.basicLabels" . | nindent 4 }}
spec:
  host: {{ include "chart.fullname" . }}
  trafficPolicy:
    loadBalancer:
      {{- if .Values.istio.useCustomLoadBalancer -}}
      {{ toYaml .Values.istio.customLoadBalancer | nindent 6 }}
      {{- else }}
      simple: {{ required "Values.istio.loadBalancerType is required if customLoadBalancer is false" .Values.istio.loadBalancerType }}
      {{- end }}
    {{- if .Values.istio.mtls.enabled }}
    tls:
      mode: ISTIO_MUTUAL
    {{- end }}
{{- end }}
