{{- if .Values.istio.enabled -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Chart.Version }}
spec:
{{- with .Values.istio.gateways }}
  gateways:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.istio.hosts }}
  hosts:
{{ toYaml . | indent 4 }}
{{- end }}
  http:
  - match:
{{- range .Values.istio.paths }}
    - uri:
       prefix: {{ . }}
{{- end }}
{{- if .Values.istio.rewrite }}
    rewrite:
      uri: {{ .Values.istio.rewrite }}
{{- end }}
    route:
    - destination:
        host: {{ .Release.Name }}
        port:
          number: {{ .Values.service.port }}


---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Chart.Version }}
spec:
  host: {{ .Release.Name }}
  trafficPolicy:
    loadBalancer:
{{- if .Values.istio.useCustomLoadBalancer -}}
  {{ toYaml .Values.istio.customLoadBalancer | nindent 6 }}
{{- else }}
      simple: {{ .Values.istio.loadBalancerType }}
{{- end }}
{{- if .Values.istio.mtls.enabled }}
    tls:
      mode: ISTIO_MUTUAL
{{- end }}
{{- end }}
