{{ if .Values.podDisruptionBudget.enabled}}
{{- if or (and (gt (.Values.replicaCount | int) 1) (not .Values.autoscale.enabled)) (and .Values.autoscale.enabled .Values.autoscale.maxPods (gt (.Values.autoscale.minPods | int) 1)) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.basicLabels" . | nindent 4 }}
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      {{- include "chart.basicSelectorLabels" . | nindent 6 }}
{{- end }}
{{ end }}