{{ if .Values.persistentVolumeClaims }}
{{- range .Values.persistentVolumeClaims }}
{{- $pvcName := (required "Each entry in persistentVolumeClaims needs a name" .name) }}
{{- $pvcFullName := printf "%s-%s" (include "chart.fullname" $ | trunc 40) $pvcName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcFullName }}
  labels:
    {{- include "chart.basicLabels" $ | nindent 4 }}
spec:
  accessModes:
  - {{ required "Each entry in persistentVolumeClaims needs an accessMode, a storageClass, and a size" .accessMode }}
  storageClassName: {{ required "Each entry in persistentVolumeClaims needs an accessMode, a storageClass, and a size" .storageClass }}
  resources:
    requests:
      storage: {{ required "Each entry in persistentVolumeClaims needs an accessMode, a storageClass, and a size" .size }}
{{- end }}
{{- end }}
