---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.basicLabels" . | nindent 4 }}
{{- if .Values.image.credentials.create }}
imagePullSecrets:
- name: {{ include "chart.fullname" . }}-registry-secret
{{- else if ne .Values.image.credentials.secretRef "" }}
imagePullSecrets:
- name: {{ .Values.image.credentials.secretRef }}
{{- end }}
