---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.basicLabels" . | nindent 4 }}
spec:
  type: {{ required "Values.service requires a type" .Values.service.type }}
  ports:
    - port: {{ required "Values.service requires a port" .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "chart.basicSelectorLabels" . | nindent 4 }}
