# pull from official PHP image with Apache
FROM php:8.1.24-apache

# Install dependencies
RUN apt-get update && apt-get install -y \
     libzip-dev \
     zip \
     supervisor \
     && docker-php-ext-install pdo pdo_mysql zip

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Copy the application code to the container
COPY . /var/www/html

# Set the working directory
WORKDIR /var/www/html

COPY /logs/laravel_err.log /var/log/laravel_err.log
COPY /logs/laravel.log /var/log/laravel.log
COPY ./docker-entrypoint.sh /

# Copy the supervisor configuration file
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Create a non-root user and give permissions to relevant directories
RUN groupadd -g 1000 limitedaccessaccount \
     && useradd -u 1000 -ms /bin/bash -g limitedaccessaccount limitedaccessaccount \
     && mkdir -p /var/www/html /var/log/supervisor /var/log/laravel \
     && chown -R limitedaccessaccount:limitedaccessaccount /var/www/html /var/log/supervisor /var/log/laravel

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer install --no-scripts --no-autoloader

# Set file permissions
RUN chown -R www-data:www-data /var/www/html \
     && chmod -R 777 /var/www/html/storage/ \
     && chmod 755 /etc/supervisor/conf.d/supervisord.conf \
     && chmod 777 /var/log/laravel_err.log \
     && chmod 777 /var/log/laravel.log \
     && chmod +x /var/www/html/docker-entrypoint.sh

# Expose port 8000
EXPOSE 8000

# Switch to non-root user
USER 1000
ENTRYPOINT ["/bin/sh"]

# Start Supervisor as non-root user
CMD ["-c", "sh /docker-entrypoint.sh"]
