###############################################################
# DOCKER IMAGE - Alpine based Nodejs Application (Express.js) #
###############################################################

FROM node:20-alpine

# Set the working directory within the container
WORKDIR /app

# copy both package.json AND package-lock.json if available
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the application code into the container
COPY . /app

# Omitting dev dependencies
RUN npm ci --omit=dev

# Create non root user
RUN addgroup -g 1050 -S limitedaccessaccount && \
    adduser -u 1050 -S limitedaccessaccount -G limitedaccessaccount

# Set non root user
USER 1050

# Expose the port that the Express.js application will run on (default is 3000)
EXPOSE 3000

# Define the command to start the Express.js application
ENTRYPOINT ["node", "app.js"]
