FROM node:18-alpine

# Install any dependencies for building & commands to use
RUN apt update && \
    apt install -y python3 make curl

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# Prepare for production build
RUN npm run prebuild

# Run the production build
RUN npm run build

# Bundle app source
COPY . .

# Create non root user
RUN addgroup -g 1050 -S limitedaccessaccount && \
    adduser -u 1050 -S limitedaccessaccount -G limitedaccessaccount

# Set non root user
USER 1050

EXPOSE 8080
CMD [ "node", "server.js" ]
